### ISSUE TITLE
same example for Ethanol molecule

### ISSUE THREAD

**Issue by thegodone** [SPARC-X/M-SPARC#2]
great paper and code. Can you provide a step to step experiment configuration for ethanol basic molecule ?
like for example :  from the input generation to 3D optimal positions of atoms

**Comment by xuqimen** [comment]
Thanks! There is a SiH4 molecule example [here](https://github.com/SPARC-X/M-SPARC/tree/master/tests/Relax/SiH4), which is very similar to what you're looking for (optimization of atom positions of a molecule). Let me know if you have any issues setting up the test.
