### ISSUE TITLE
Keep encountering this error....

### ISSUE THREAD

**Issue by gin-kou** [SPARC-X/M-SPARC#23]
Hi, could someone help me with this issue....I keep encountering this whenever I run my inpt file for structural relaxation of graphite.....

Error using cell_relax>Brent (line 302)
Root must be within the given range (x1, x2) in Brent's method

Error in cell_relax (line 28)
[optVol,S,~] = Brent(@volume_relax_fun, S, lower_bound, upper_bound, 1e-4, S.TOL_RELAX_CELL, S.max_relax_it);

Error in relax (line 41)
		S = cell_relax(S);

Error in msparc (line 67)
	S = relax(S);

# INPT FILE......

#Test: Graphite 
#LATVEC SCALE FINAL: 4.65028 4.65028 16.35160

LATVEC_SCALE: 4.7 4.7 16
LATVEC:
1.0000000000         0.0000000000         0.0000000000
-0.500000000         0.8660254037         0.0000000000
0.0000000000         0.0000000000         1.0000000000
MESH_SPACING: 0.3
FD_ORDER: 12
BC: P P P
EXCHANGE_CORRELATION: LDA_PZ
TOL_SCF: 1e-6

RELAX_FLAG: 2
RELAX_METHOD: LBFGS
RELAX_MAXDILAT: 1.1
RELAX_NITER: 10
PRINT_RELAXOUT: 1
PRINT_FORCES: 1
PRINT_ATOMS: 1
CALC_STRESS: 1

# ION FILE.....

ATOM_TYPE: C                             # atom type 
N_TYPE_ATOM: 4                              # number of atoms of this type
PSEUDO_POT: C.psp8     # pseudopotential
COORD:                                      # coordinates follows
     0.000000000         2.713546236         4.000000000
     2.349999765         1.356772997        12.000000000
     0.000000000         0.000000000         4.000000000
     0.000000000         0.000000000        12.000000000

For the pseudopotential I used the one provided in the package.....
Thanks in advance......

**Comment by gin-kou** [comment]
Update: I ran the same structural relaxation on a test example (MoS2) instead of my written input file and it still shows the same error.....

**Comment by xuqimen** [comment]
Hi @gin-kou,

I see that you are using `RELAX_FLAG: 2`, which is intended for volume optimization, where the cell shape is fixed and the cell dimensions in all directions are varied proportionally (note that atom positions are scaled proportionally too) to look for an optimal cell volume. This type of geometry optimization algorithm is suited for structures such as FCC, BCC structures, etc., whose relative atom positions and cell shapes are known, and the only degree of freedom is the volume of the unit cell.

In your case, there are 2 degrees of freedom in the cell dimensions. To be more specific, cell dimensions are in the form of [a,a,c], where the parameters `a` and `c` are to be optimized independently. Also, I'm assuming the distance between the layers is also to be relaxed, so atoms have to be moved in the z-direction independently as well. This type of geometry optimization is not implemented in the current M-SPARC code yet, which shall be done in the near future. @abhirajsharma may know more about this.

That being said, you can always implement your own optimization algorithm, while using M-SPARC as a single-point DFT solver that can provide energy, forces, and stress tensor for any given atomic configuration, which are usually all you need in a geometry optimization algorithm.

Regards,
Qimen

**Comment by gin-kou** [comment]
Hi Qimen,

Thanks for your quick response!
Thanks for clarifying. I shall try writing my own script to optimize for a hexagonal structure (a and c separately).
Wishing you a wonderful day!

Regards,
gin-kou

**Comment by xuqimen** [comment]
Hi gin-kou,

I'm glad to help! In case it helps, if you are interested in calling your own geometry optimization algorithm within M-SPARC, you can add another `elseif` condition before [this line](https://github.com/SPARC-X/M-SPARC/blob/master/src/relax.m#L42) and call your optimization function. This way, the DFT solutions of the previous optimization step can be automatically used to accelerate the DFT solver in every optimization step.

Regards,
Qimen

**Comment by gin-kou** [comment]
Thank you for the suggestion! I shall do that.
