### ISSUE TITLE
Can't read pseudopotential file

### ISSUE THREAD

**Issue by shivangag97** [SPARC-X/M-SPARC#7]
Hello,

I was trying to use the code for structural relaxation of calcium phosphate clusters but ran into some pseudopotential issues.  downloaded all the pseudopotentials for Ca, P, and O from [this](https://www.abinit.org/psps_abinit) site. However, when I run M-SPARC, MAT:AB throws up the following error that I am unable to understand:

```
Index exceeds matrix dimensions.

Error in readPseudopot (line 50)
		r = A(2,:)' ;

Error in initialization (line 28)
		S = readPseudopot(S, ityp, S.Atm(ityp).psdfname, S.Atm(ityp).typ);

Error in msparc (line 34)
S = initialization(fname);
```

Could you kindly let me know how to get past this issue? I would be highly grateful and it would really help me out.

Thanks and regards,
Shivang

**Comment by xuqimen** [comment]
Hi Shivang,

Thanks for noticing us about this issue. The major reason why this happens is that the pseudopotentials you obtained from the ABINIT website have nonlinear core correction (NLCC), which can be verified by line 4 of the pseudopotential file, where the `fchrg` value is nonzero. We were aware of this and had implemented the NLCC in M-SPARC in a development version, although we have not updated it in this release. If it's necessary for you to use NLCC, we could update it sometime soon. For the time being, I suggest you try the SG15 pseudopotentials which do not contain NLCC. You can get the psp8 format of these pseudopotentials [here](https://github.com/xuqimen/SG15_pseudopotentials_psp8_upf/tree/master/PBE_psp_cut).

Apart from the NLCC issue, some pseudopotentials from the [ABINIT website](https://www.abinit.org/psps_abinit) you mentioned, have a slightly different format than the other psp8 formats, by including fewer columns of data in the very last block. This could also result in a failure in the pseudopotential reading. It should not be hard to have a fix for this either. But it is not dealt with in the current release.

Regards,
Qimen

**Comment by shivangag97** [comment]
Hi Qimen,

Thank you so much for your quick reply, the information, and for the link. It works now. I appreciate the help!

Best,
Shivang

**Comment by xuqimen** [comment]
Hi Shivang,

You're welcome, I'm glad to help!

Regards,
Qimen
